kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: overseerr-config-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
