---
addic7ed:
  cookies: ''
  password: ''
  user_agent: ''
  username: ''
  vip: false
analytics:
  enabled: false
anticaptcha:
  anti_captcha_key: ''
assrt:
  token: ''
auth:
  apikey: ${SECRET_BAZARR_API_KEY}
  password: ''
  type: null
  username: ''
backup:
  day: 6
  folder: /backup
  frequency: Weekly
  hour: 2
  retention: 31
betaseries:
  token: ''
cors:
  enabled: true
deathbycaptcha:
  password: ''
  username: ''
embeddedsubtitles:
  hi_fallback: false
  included_codecs: []
  timeout: 600
  unknown_as_english: false
general:
  adaptive_searching: false
  adaptive_searching_delay: 1w
  adaptive_searching_delta: 3d
  anti_captcha_provider: null
  auto_update: false
  base_url: /bazarr
  branch: master
  chmod: '0640'
  chmod_enabled: false
  days_to_upgrade_subs: 40
  debug: false
  default_und_audio_lang: ''
  default_und_embedded_subtitles_lang: ''
  dont_notify_manual_actions: false
  embedded_subs_show_desired: true
  embedded_subtitles_parser: ffprobe
  enabled_providers:
  - gestdown
  - opensubtitlescom
  flask_secret_key: 7e3dfa2fe2e6cfc8ceff62b2b89e3e0f
  hi_extension: hi
  ignore_ass_subs: false
  ignore_pgs_subs: false
  ignore_vobsub_subs: true
  ip: 0.0.0.0
  language_equals: []
  minimum_score: 95
  minimum_score_movie: 80
  movie_default_enabled: true
  movie_default_profile: 1
  multithreading: true
  page_size: 50
  page_size_manual_search: 20
  parse_embedded_audio_track: true
  path_mappings: []
  path_mappings_movie: []
  port: 6767
  postprocessing_cmd: ''
  postprocessing_threshold: 90
  postprocessing_threshold_movie: 70
  serie_default_enabled: true
  serie_default_profile: 1
  single_language: false
  skip_hashing: false
  subfolder: current
  subfolder_custom: ''
  subzero_mods: OCR_fixes,common,fix_uppercase
  theme: auto
  upgrade_frequency: 12
  upgrade_manual: true
  upgrade_subs: true
  use_embedded_subs: true
  use_postprocessing: false
  use_postprocessing_threshold: false
  use_postprocessing_threshold_movie: false
  use_radarr: true
  use_scenename: true
  use_sonarr: true
  utf8_encode: true
  wanted_search_frequency: 6
  wanted_search_frequency_movie: 6
hdbits:
  passkey: ''
  username: ''
karagarga:
  f_password: ''
  f_username: ''
  password: ''
  username: ''
ktuvit:
  email: ''
  hashed_password: ''
legendasdivx:
  password: ''
  skip_wrong_fps: false
  username: ''
movie_scores:
  audio_codec: 3
  edition: 1
  hash: 119
  hearing_impaired: 1
  release_group: 13
  resolution: 2
  source: 7
  streaming_service: 1
  title: 60
  video_codec: 2
  year: 30
napisy24:
  password: ''
  username: ''
opensubtitles:
  password: Pandora1
  skip_wrong_fps: false
  ssl: false
  timeout: 15
  use_tag_search: false
  username: noppes666
  vip: false
opensubtitlescom:
  include_ai_translated: false
  password: Pandora1
  use_hash: true
  username: noppes666
podnapisi:
  verify_ssl: true
postgresql:
  database: ''
  enabled: false
  host: localhost
  password: ''
  port: 5432
  username: ''
proxy:
  exclude:
  - localhost
  - 127.0.0.1
  password: ''
  port: ''
  type: null
  url: ''
  username: ''
radarr:
  apikey: def66c0449264a8d8e3722c34ff1f6f0
  base_url: /radarr
  defer_search_signalr: false
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 6
  http_timeout: 60
  ip: radarr-svc.media
  movies_sync: 60
  only_monitored: false
  port: 80
  ssl: false
  sync_only_monitored_movies: false
  use_ffprobe_cache: true
series_scores:
  audio_codec: 3
  episode: 30
  hash: 359
  hearing_impaired: 1
  release_group: 14
  resolution: 2
  season: 30
  series: 180
  source: 7
  streaming_service: 1
  video_codec: 2
  year: 90
sonarr:
  apikey: 965f0c834f3a4eaf8ab9f74fa8927b52
  base_url: /sonarr
  defer_search_signalr: false
  episodes_sync: 15
  exclude_season_zero: true
  excluded_series_types: []
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 5
  http_timeout: 60
  ip: sonarr-svc.media
  only_monitored: false
  port: 80
  series_sync: 60
  ssl: false
  sync_only_monitored_episodes: false
  sync_only_monitored_series: false
  use_ffprobe_cache: true
subf2m:
  user_agent: ''
  verify_ssl: true
subscene:
  password: ''
  username: ''
subsync:
  checker:
    blacklisted_languages: []
    blacklisted_providers:
    - whisperai
  debug: false
  force_audio: true
  gss: true
  max_offset_seconds: 60
  no_fix_framerate: true
  subsync_movie_threshold: 70
  subsync_threshold: 90
  use_subsync: true
  use_subsync_movie_threshold: false
  use_subsync_threshold: false
titlovi:
  password: ''
  username: ''
titulky:
  approved_only: false
  password: ''
  username: ''
whisperai:
  endpoint: http://whisper-svc.automatiom.svc.cluster.local
  loglevel: INFO
  response: 5
  timeout: 3600
xsubs:
  password: ''
  username: ''

