apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: prowlarr-backup-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Mi # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: prowlarr.backup#
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media-backup/prowlarr'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-backup-pvc
spec:
  volumeName: prowlarr-backup-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Mi # Dummy value
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
