---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: readarr-external
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`media.${SECRET_DOMAIN_0}`) && PathPrefix(`/readarr`)"
      kind: Rule
      services:
        - name: readarr-svc
          port: 80
      # middlewares:
      #   - name: default-headers
        # - name: readarr-strip-prefix
        #   namespace: "{{readarr_namespace}}"
  tls: {}
