---
apiVersion: v1
kind: Service
metadata:
  name: calibre-ui-svc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: calibre
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-admin-svc
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: calibre
  # type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web-svc
spec:
  ports:
    - name: calibre-web
      port: 8083
      targetPort: 8083
  selector:
    app: calibre
  type: LoadBalancer
