      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: sonarr-external
        annotations:
          kubernetes.io/ingress.class: traefik-external
      spec:
        entryPoints:
          - websecure
        routes:
          - match: "Host(`media.${SECRET_DOMAIN_0}`) && PathPrefix(`/sonarr`)"
            kind: Rule
            services:
              - name: sonarr-svc
                port: 80
        tls: {}
