---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: sonarr-tv-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Mi # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: homenas.home/tv##
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media/media/tv'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-tv-pvc
spec:
  volumeName: sonarr-tv-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi # Dummy value
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: sonarr-downloads-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Mi # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: homenas.home/sonarr##
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media/usenet/complete'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-downloads-pvc
spec:
  volumeName: sonarr-downloads-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi # Dummy value
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: sonarr-backup-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Mi # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: sonarr.backup
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media-backup/sonarr'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-backup-pvc
spec:
  volumeName: sonarr-backup-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Mi # Dummy value
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-config-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
