---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./volumes.yaml
  - ./service.yaml
  - ./ingressroute.yaml
  - ./deployment.yaml
configMapGenerator:
  - name: radarr-config
    files:
      - config.xml
generatorOptions:
  disableNameSuffixHash: true
