---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: radarr-media-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Ti # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: radarr.media
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-media-pvc
spec:
  volumeName: radarr-media-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti # Dummy value
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: radarr-backup-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Mi # Dummy value
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: radarr.backup##
    volumeAttributes:
      source: '//${CONFIG_NFS_SERVER_IP_ADDRESS}/media-backup/radarr'
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-backup-pvc
spec:
  volumeName: radarr-backup-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi # Dummy value
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
